# Script Dockerfile
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install dependencies
RUN pip install requests

# Copy the script into the container
COPY fetch_statistics.py .

# Command to run the script
CMD ["python", "fetch_statistics.py"]